
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository --show-version"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml"

cache:
  paths:
    - .m2/repository

image: adoptopenjdk:11-jdk-hotspot

stages:
  - build


build:
  stage: build
  script:
    - >
      if [[ $CI_COMMIT_BRANCH =~ ^feature- ]]; then
       ./mvnw versions:set -DremoveSnapshot -DprocessAllModules
       ./mvnw versions:set -DnewVersion=\${project.version}-$CI_COMMIT_BRANCH-SNAPSHOT -DprocessAllModules
      fi
    - './mvnw clean deploy $MAVEN_CLI_OPTS'
  artifacts:
    paths:
      - target/*.jar
      - target/*.zip
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG =~ /^release-/'
    - if: '$CI_COMMIT_BRANCH =~ /^feature-/'
